training:
  epochs: 50
  lr: 0.01
  optimizer: SGD
  momentum: 0.9
  weight_decay: 0.0001
  scheduler: StepLR
  step_size: 10
  gamma: 0.1
model:
  backbone: resnet50
  pretrained: true
loss:
  cls: focal
  reg: smooth_l1
  lambda_mcl: 0.0  # No MCL in base
checkpoint_dir: checkpoints/base/
log_dir: logs/base/ 
